FROM public.ecr.aws/lambda/python:3.9

RUN pip install -U pip
RUN pip install pdm

COPY pyproject.toml pdm.lock /

RUN pdm install --prod --no-self --no-lock --no-editable

# Copy data directory
COPY data data

# Copy function code
COPY src/python app

# Add venv to PATH
ENV PATH=/.venv/bin:$PATH
# Set python path
ENV PYTHONPATH=app


# Set the CMD to your handler (could also be done as a parameter override outside of the Dockerfile)
CMD [ "app.api.mangum_handler.handler" ]