[GLOBAL]
pants_version = "2.15.0"

backend_packages = ["pants.backend.python", "pants.backend.awslambda.python"]

[python]
interpreter_constraints = ["CPython==3.9.*"]

[source]
root_patterns = [
    # '/3rdparty/python',
    '/src/python',
    '/src/docker',
    #   '/tests/python',
]
