[GLOBAL]
pants_version = "2.15.0"

backend_packages = ["pants.backend.python"]

[python]
interpreter_constraints = ["==3.10.*"]

[source]
root_patterns = [
    # '/3rdparty/python',
    '/src/python',
    '/src/docker',
    #   '/tests/python',
]
