---
name: Create map from STAC Item
on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '40 0 * * *'
jobs:
  update-map:
    runs-on: ubuntu-latest
    env:
      SOURCE_PATH: src/python
      SCRIPT_NAME: cli.py

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.9.*
          cache: pip
      - run: pip install -r requirements.txt
      - run: PYTHONPATH=$SOURCE_PATH python $SOURCE_PATH/stac_tiler_map/$SCRIPT_NAME
      - uses: EndBug/add-and-commit@v9
        with:
          message: "Update map"
          default_author: github_actions
