name: Run Tests

on:
  - workflow_dispatch
  - push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up PDM
        uses: actions/setup-pdm@v3
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: pdm install
      - name: Test with pytest
        run: |
          pytest